name: Publish to Packagist

on:
  push:
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Packagist
        run: |
          curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&api_token=${{ secrets.PACKAGIST_API_TOKEN }}" -d'{"repository":{"url":"https://packagist.org/packages/a3soft/a3pay-php-client"}}'
